--- # MariaDB user management file: roles/mysql/tasks/manage_users.yml

- name: Managing MariaDB users
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    append_privs: "{{ item.append_privs | default(omit) }}"
    update_password: "{{ item.update_password | default(omit) }}"
  with_items: "{{ mysql_users }}"
